Make-IT-TSUKUBA/alternative-tsukuba-kdb

index.html
script.js
style.css

題名の通りです。
また、ラジオボタンを増設した影響などでcssも少しいじりました。
一部ゴリ押し気味のコードがある気がするのでもし余裕があれば/改善するところがあればリファクタリングしていただけるとありがたいです。
この機能を追加した状態のものは以下のリンクで見れるはずです。
https://maru2213.github.io/alternative-tsukuba-kdb/

標準履修年次で検索する機能を追加

---

index.html
script.js
style.css

スマートフォンからの表示だと、入力フォームの部分が見切れてしまうため、対応しました。
表示画面が限られていますので、1100px以下の場合はメディアクエリで分岐し、
ラジオボタン→セレクトボックスとして表示しています。

入力フォームのレスポンシブデザインへの対応

---

index.html
script.js
style.css

曜日及び時限の選択に関するUIをカレンダー形式に変更しました。
また、複数コマの選択に対応しました。

曜日・時限選択のUI変更

---

index.html
script.js
style.css

時限による絞り込みの他に、集中・応談・随時での選択に対応しました。
加えて、スタイルの軽微な修正を行いました。

集中・応談・随時に対応

---

script.js

検索条件をクリアで、req-Bとreq-Cの選択が削除されないので削除されるようにしました。また、CSVファイルを生成するときのfor文でvarが省略されていたので、追記しておきました。

検索要件をまとめてクリアできるようにする

---

index.html
script.js
style.css

「シラバス」ボタンの横にある★を押すことで、授業をお気に入りとして登録可能にしました。お気に入りの中でのみ検索することも可能です。
[こちらから試すことができます。](https://itsu-dev.github.io/alternative-tsukuba-kdb/)
（リファクタリング中でしたらごめんなさい）

お気に入り機能を実装

---

script.js

検索条件をクリアしたときに、selectedPeriodsが初期化されていなくて条件がクリアできないため修正しました。ついでにセミコロンがついていない箇所を修正しました。

タイムテーブルの設定がクリアされるように修正

---

.github/workflows/main.yml

fix: #25 
Pushする際の権限の問題を解決するため、APIからPushするActionを導入しました。上手く行けばいいのですが。

Fix: push with token

---

index.html

Add: repo link to footer

---

src/download.py

Add: Error handler for kdb failure

---

src/download.py

Fix: response var name

---

.github/workflows/main.yml

Protected Branch+Required approving reviewsにしている以上、承認が必要になるようなので毎回PRを作成するように変更しました。

シラバスの更新PRを作成するように変更

---

src/index.scss

Sassで書き換えた際に指定をミスっていたので修正
修正前
修正後

modify the style of the keyword input

---

src/index.scss
src/main.ts

- 1100px以下のデバイスで検索ボタンが反応しない問題を修正しました
- `-webkit-text-size-adjust: 100%;` を追加しました
- サンプル：https://inaniwaudon.github.io/kdb-ts/

1100px以下のデバイスでの検索ボタンのバグ修正

---

.github/workflows/main.yml
tools/python/csv-json.py
tools/python/download.py

- CSV scheduled update の GitHub Actions が生成する JSON データが ./tools 下に生成されていたため、./src に生成されるように変更
- mergeされていなかった過去のシラバスデータを手動で追加

シラバスデータの更新およびCIの修正

---

.github/workflows/main.yml

main.yml の修正

---

.github/workflows/build-deploy.yml

#106 で 間違えて `pull_request` の方を残していました　すみません

プルリクを作成した段階でデプロイされてしまう

---

script.js
src/subject/render.ts
tools/python/download.py

2022年度版のシラバスが公開されたので、リンクも2022年度版のものに更新しました。

Updated syllabus URL to 2022

---

script.js
src/subject/search.ts

input 内に入力された大文字・小文字を区別しないようにしました。
script.js は Prettier が走ってるだけで手付かずです
Closes #118

ケースインセンシティブな検索

---

src/bookmark.ts
src/style/bookmark.scss
src/subject/index.ts
src/subject/render.ts

時間割からシラバスにリンクを追加

---

script.js
src/main.ts
src/subject/index.ts
src/subject/search.ts

#96 で報告されていた問題を修正しました。
- ● 春 ◯ 秋 ／ ● A ◯ B ◯ C を選択すると、｢春C／秋A」の科目がマッチしてしまう。

モジュールによる検索を修正

---

src/bookmark.ts
src/style/bookmark.scss
src/subject/index.ts
src/subject/render.ts

授業の実施形態に合わせて、カレンダーを以下の通りに色付けしました。
- 対面の場合は赤
- オンラインの場合は青
- 対面・オンライン併用の場合は紫
- 不明の場合は無彩色（グレー）
また、現在の日時に合わせてカレンダーを自動で切り替えるようにしました。
例えば、現在であれば秋Aのカレンダーが自動表示されます。

Fix online

---

.github/workflows/build-deploy.yml

open-ssl 関連のエラーっぽい
https://qiita.com/akitkat/items/f455bbc088a408cbc3a5
fix: https://github.com/Make-IT-TSUKUBA/alternative-tsukuba-kdb/issues/173

デプロイの CI が落ちていたのを修正

---

src/index.html
src/timetable.ts

「検索条件をクリア」を押した際に「ブックマークを除外」のチェックボックスをはずすように改善

「検索条件をクリア」の挙動を修正

---

.prettierignore
src/code-types.json
tools/python/csv-json.py

Update of syllabus data (2023-10-04)

---

README.md
src/bookmark.ts

fix: #204 
`e.preventDefault()` しました。

時間割のリンクを修正

---

.github/workflows/test.yml
.github/workflows/update-syllabus.yml

シラバスの更新の PR の auto-merge を有効にします。

auto-merge を有効にする

---

.github/workflows/pr-review.yml
.github/workflows/update-syllabus.yml

Actions が作成した PR を自動でレビューし、auto-merge が働くようにします。

Actions が作成した PR を自動でレビューする

---

.github/workflows/update-syllabus.yml

GitHub Actions が作成した PR に Actions は反応しないっぽい？

admin として PR を作成

---

.github/workflows/update-syllabus.yml

https://zenn.dev/yuma_prog/articles/actions_trigger-by-githubtoken

PR を管理者権限で作成

---

src/subject/index.ts

2024 年度版シラバスに対応

---

tools/python/download.py

スクリプトのバグ修正

---

.github/workflows/update-syllabus.yml
README.md
tools/README.md
tools/python/code-types-grad.py

マージされず close した科目データ更新の PR に含まれていた csv ファイルを追加します。
- 例：https://github.com/Make-IT-TSUKUBA/alternative-tsukuba-kdb/pull/657
合わせて、`/tools/csv` にあった科目データを `/csv` に移しました。

欠落していた科目データを追加

---

frontend/src/App.tsx
frontend/src/components/Footer.tsx
frontend/src/components/Main/Main.tsx
frontend/src/components/Timetable/Index.tsx
frontend/src/utils/subject.ts
frontend/src/utils/useBookmark.ts

fix: #681 
CSV ダウンロード機能が機能しなくなっていたバグ（実装忘れ）を修正します。

CSV ダウンロードを修正

---

.github/workflows/update-syllabus.yml

CI が落ちていたので Python のバージョンを修正
https://github.com/Make-IT-TSUKUBA/alternative-tsukuba-kdb/actions/runs/14223190785

Python をアップデート

---

frontend/package.json
frontend/src/App.tsx
frontend/src/components/Main/ClassroomImport.tsx
frontend/src/components/Main/Main.tsx
frontend/src/components/Main/MainTableDesktop.tsx
frontend/src/components/Main/SubjectTr.tsx
frontend/src/utils/style.ts
frontend/src/utils/useBookmark.ts
frontend/src/utils/useClassroom.ts
frontend/yarn.lock

教室情報のインポート機能を追加しました．ユーザがインポートしたデータを LocalStorage に保存します．
fix: #716

教室情報のインポート機能を追加
